apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: local-kafka-poc
build:
  artifacts:
  - image: kafkajs-client
    docker:
      dockerfile: Dockerfile
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
    - ../../deploy/namespace.yaml
    - ../../deploy/cluster-operator/*.yaml
    - ../../deploy/kafka-cluster-tls.yaml
    - ../../deploy/topics.yaml
    - ../../deploy/producer-user.yaml
    - ../../deploy/consumer-user.yaml
    - ../../deploy/kafkajs-client.yaml

    flags:	# 	additional flags passed to kubectl.
      global: ["-n", "kafka"]
