apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-go-client
  labels:
    app: kafka-go-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-go-client
  template:
    metadata:
      labels:
        app: kafka-go-client
    spec:
      containers:
      - name: kafka-go-client
        image: kafka-go-client:latest
        volumeMounts:
        - name: client-certs
          mountPath: "/client-certs"
          readOnly: true
        - name: ca-certs
          mountPath: "/ca-certs"
          readOnly: true
      volumes:
      - name: client-certs
        secret:
          secretName: test-producer-01
          optional: false
      - name: ca-certs
        secret:
          secretName: my-cluster-cluster-ca-cert
          optional: false