apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: kafka-connect
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: kafka-connect
          patternType: prefix
        operation: All
        host: "*"
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: my-topic.replica
          patternType: literal
        operation: All
        host: "*"
      - resource:
          type: topic
          name: _confluent
          patternType: prefix
        operation: All
        host: "*"
      - resource:
          type: topic
          name: __consumer_timestamps
          patternType: literal
        operation: All
        host: "*"
      - resource:
          type: group
          name: kafka-connect
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: group
          name: confluent-replicator
          patternType: literal
        operation: Read
        host: "*"
